### ISSUE TITLE
Lock down iris couchdb instance

### ISSUE THREAD

**Issue by eightysteele** [eightysteele/Spatial-Data-Library#36]
Heh.

**Comment by eightysteele** [comment]
@tucotuco: Bump.

**Comment by tucotuco** [comment]
Well, http://wiki.apache.org/couchdb/Security_Features_Overview says:

"Note: If there are any reader names or roles defined for a database, then only authenticated users having a matching name or role are allowed to read documents from the database (or do a GET /db_name/ call)."

and

"Having no readers, any user can write regular documents (any non-design document) and read documents from the database."

So I tested these hypotheses. Indeed, if there is a reader user, then authentication is required to write and to read from the db. Otherwise it isn't. There are only three types of users - server admins, database admins, and database readers. Readers, despite the name, "can read all types of documents from the DB, and they can write (and edit) documents to the DB except for design documents." There is no user type that can just read from a database.

For now I set the worldclim database to have ["tuco","eighty","eightysteele"] as admins and readers. Can't see these databases on spatial.iriscom unless logged in. For simplicity, I'll just turn that security off to do replication. App Engine will have to authenticate when it reads from Couch.

**Comment by eightysteele** [comment]
> App Engine will have to authenticate when it reads from Couch.

What authentication method is required for readers?

**Comment by tucotuco** [comment]
See Authentication section of http://wiki.apache.org/couchdb/Security_Features_Overview

**Comment by eightysteele** [comment]
@tucotuco confirmed basic HTTP authentication. Closing issue.
